version: '3'

services:
   web:
      build: .
      volumes:
         - .:/code
      restart: always
      expose: 
         - 8000
      user: 1001:1002
      command: python /code/manage.py runserver 0.0.0.0:8000

   nginx: 
      restart: always
      build: ./nginx/
      depends_on: 
         - web
      ports: 
         - 80:80
      links:
         - web:web
