# Generated by Django 4.1.1 on 2022-10-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeFitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprofile',
            name='currentWeight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fitnessprofile',
            name='currentheight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fitnessprofile',
            name='goalWeight',
            field=models.IntegerField(),
        ),
    ]
