# Generated by Django 4.1.2 on 2022-11-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LifeFitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.AddField(
            model_name='workout',
            name='exerciseName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LifeFitness.exercise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
