# Generated by Django 4.1.1 on 2022-10-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeFitness', '0002_alter_fitnessprofile_currentweight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessprofile',
            name='BMI',
        ),
        migrations.RemoveField(
            model_name='fitnessprofile',
            name='currentWeight',
        ),
        migrations.RemoveField(
            model_name='fitnessprofile',
            name='currentheight',
        ),
        migrations.RemoveField(
            model_name='fitnessprofile',
            name='goalWeight',
        ),
    ]
