# Generated by Django 4.1.2 on 2022-12-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeFitness', '0002_remove_workout_description_remove_workout_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout_session',
            old_name='exerciseList',
            new_name='workoutList',
        ),
    ]
