# Generated by Django 4.1.1 on 2022-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeFitness', '0003_rename_exerciselist_workout_session_workoutlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_session',
            name='date',
            field=models.DateField(),
        ),
    ]
