# Generated by Django 4.1.1 on 2022-10-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeFitness', '0003_remove_fitnessprofile_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='BMI',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='currentWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='currentheight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='goalWeight',
            field=models.IntegerField(default=0),
        ),
    ]
