# Generated by Django 4.1.2 on 2022-10-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeFitness', '0004_fitnessprofile_bmi_fitnessprofile_currentweight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessprofile',
            name='BMI',
            field=models.IntegerField(default=0),
        ),
    ]
