# Generated by Django 4.1.1 on 2022-11-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeFitness', '0005_alter_fitnessprofile_bmi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessprofile',
            old_name='FitnessUser',
            new_name='fitnessUser',
        ),
    ]
